name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable

      - name: Build Rust project
        run: cargo build --release

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Verify deploy.sh file existence
        run: |
          pwd
          ls -la deploy.sh

      - name: Make deploy.sh executable
        run: chmod +x deploy.sh

      - name: Execute deploy.sh
        run: ./deploy.sh
