name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable

      - name: Build Rust project
        run: cargo build --release

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t basic_rust_api_image .

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 Instance and Deploy
        run: |
          ssh -v -o StrictHostKeyChecking=no \
          "${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_HOST }}" \
          'bash -s' < deploy.sh