name: Deploy to AWS EC2

on:
  push:
    branches: [ main ] # Adapt this to your branch trigger strategy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS (Replace with AWS Secrets Manager approach)
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install Docker CLI (if needed)
        run: |
          sudo yum install docker -y || sudo apt-get install docker-ce -y

      - name: Get SSH key from Secrets Manager
        uses: aws-actions/aws-secretsmanager@v7
        with:
          secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Connect to EC2 instance (using retrieved SSH key)
        run: |
          # Decode and add the retrieved SSH key to the agent
          echo ${{ steps.get-secret.outputs.SecretString }} | base64 -d > key.pem && chmod 0400 key.pem && ssh-agent bash -c "ssh-add key.pem && ssh ec2-user@${{ secrets.EC2_INSTANCE_ID }}"

      - name: Build Docker image
        run: |
          docker build -t basic-rust-api .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 basic-rust-api

